### ISSUE TITLE
shell commands must be escaped

### ISSUE THREAD

**Issue by rekado** [brummer10/GxSlowGear.lv2#1]
In the Makefile the check whether to use SSE instructions is broken because shell commands must be enclosed in `$(shell ...)`.

So this block...

```
    ifneq (cat /proc/cpuinfo | grep sse2 >/dev/null,)
    SSE_CFLAGS = -msse2 -mfpmath=sse
    else ifneq (cat /proc/cpuinfo | grep sse >/dev/null,)
    SSE_CFLAGS = -msse -mfpmath=sse
    else
    SSE_CFLAGS = ""
    endif
```

would turn into...

```
    ifneq ($(shell cat /proc/cpuinfo | grep sse2 >/dev/null),)
    SSE_CFLAGS = -msse2 -mfpmath=sse
    else ifneq ($(shell cat /proc/cpuinfo | grep sse >/dev/null),)
    SSE_CFLAGS = -msse -mfpmath=sse
    else
    SSE_CFLAGS =
    endif
```

Also note that `SSE_CFLAGS = ""` was changed to `SSE_CFLAGS =`.

The same problem exists in GxVintageFuzzMaster.lv2, GxVoodooFuzz.lv2, GxSaturator.lv2, GxSuperFuzz.lv2, GxSwitchlessWah.lv2, GxHyperion.lv2.

Without this fix the plugins cannot be built for armhf and mips64el.

(BTW: I've packaged all of your plugins for GNU Guix.)

**Comment by brummer10** [comment]
Hi rekado

Thanks for the hint, I've forgotten about that.
Note that on ARM devices you need full double support for most of the plugs, on armv7 you could ensure that with the  -mfpu=vfpv3 flag ( don't use vfpv4). I've replaced the SSE check ( in all plugs) with a proper CPU check now, and set -mfpu=vfpv3 as default when a armv7 is found. 

Good to know that you find the plugs useful enough to pack them for GNU Guix.

regards
hermann
